version: '3.9'

services:
  db:
    image: postgres:15
    container_name: subscription-db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./migrations.sql:/docker-entrypoint-initdb.d/migrations.sql

  app:
    build: .
    container_name: subscription-service
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  db_data:
